# ===================================================================
# GENERAL PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  application:
    name: healthy-food-template
  main.banner-mode: off
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthyFood
    username: root
    password: root
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.ddl-auto: update

# ===================================================================
# MAIL PROPERTIES
# ===================================================================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ulquiorra.kurosaki50@gmail.com
    password: urzxuqfyrrqtdyiw
    server:
      protocol: smtp
      debug: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    enabled: true
    template-loader-path: classpath:/templates

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
# ===================================================================
# SECURITY PROPERTIES
# ===================================================================
security:
  jwt:
    Key: llaveperrona
    lifeTime: 10000

# ===================================================================
# LOG PROPERTIES
# ===================================================================
logging:
  pattern:
    file: '[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p'
    console: "%p, %d{'yyyy-MM-dd HH:mm:ss,SSS',America/Mexico_City}, %C{1}:%M:%L, %X{mdc.uuid}, %m%n%ex{3}"
  level:
    com.moontech.library: DEBUG
    org:
      springframework.data: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

# ===================================================================
# URL ENDPOINTS
# ===================================================================
api:
  uri:
    domain:
      users: /users
      offices: /offices
      supplier: /suppliers
      parameters: /parameters
      units: /units
      profiles: /profiles
      appointments: /appointments
      customers: /customers
    data:
      modified: /{id}
      search: /{search}
      initial: /initial
      authentication: ${api.uri.domain.users}/authentication
      profile: /profile
      customer:
        appointments: /{idCustomer}${api.uri.domain.appointments}
  interceptorPath: "/**"
  # ===================================================================
  # MAIL TEMPLATE PROPERTIES
  # ===================================================================
  mail:
    templates:
      user: email-user-template.flth
      customer: email-customer-template.flth
      payment: email-payment-subscription-template.flth
    welcome: Bienvenido
    from: felipemonzon2705@gmail.com
    payment: Tu Recibo de la Membresía
    helpMessage: Estamos muy contentos de poder satisfacer sus necesidades de nutrición. Si tiene alguna pregunta sobre la suscripción o si surge algún problema en el futuro, puede comunicarse con nosotros al 667 100 0000 o enviar un correo electrónico a felipemonzon2705@gmail.com

# ===================================================================
# SWAGGER PROPERTIES
# ===================================================================
swagger:
  basePackage: com.moontech
  title: SERV-healthy-food-service
  descriptionApi: Gestion y administracio de nutriologos.
  version: 1.0.0
  nameDeveloper: Felipe Monzon
  contactUrl: https://felipemonzon.github.io/
  emailDeveloper: felipemonzon2705@gmail.com