# ===================================================================
# GENERAL PROPERTIES
# ===================================================================

spring:
  flyway:
    locations: classpath:db/migration/
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
