CREATE TABLE address (
  id BIGINT NOT NULL AUTO_INCREMENT,
  street VARCHAR(100) NOT NULL,
  num_int VARCHAR(10) NOT NULL,
  num_ext VARCHAR(10),
  between_streets VARCHAR(100) NOT NULL,
  reference VARCHAR(100) NOT NULL,
  id_user BIGINT NOT NULL,
  id_suburb BIGINT NOT NULL,
  PRIMARY KEY PK_ADDRESS (id),
  CONSTRAINT FK_ADDRESS_USERS FOREIGN KEY (id_user) REFERENCES users (id),
  CONSTRAINT FK_ADDRESS_SUBURB FOREIGN KEY (id_suburb) REFERENCES suburbs (id)
);